CREATE TABLE IF NOT EXISTS Run (
id SERIAL PRIMARY KEY,
title VARCHAR(255) NOT NULL,
startedOn TIMESTAMP NOT NULL,
endedOn TIMESTAMP NOT NULL,
miles DECIMAL(5, 2) NOT NULL,
location VARCHAR(255) NOT NULL
);
